name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: 1. Unit Tests
        run: pytest tests/unit_test.py

      - name: 2. Linting (Flake8)
        run: flake8 src/

  deployment-stage:
    needs: commit-stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 3. Build & Package (Docker)
        run: docker build -t ml-service:latest .

      - name: 4. Component Test
        run: |
          pip install -r requirements.txt
          pytest tests/integration_test.py

      - name: 5. Smoke Test (Deployment Verification)
        run: |
          docker run -d -p 5000:5000 --name prediction-service ml-service:latest
          sleep 15
          # Konteynır loglarını göster (Eğer hata varsa burada göreceğiz)
          docker logs prediction-service
          pytest tests/smoke_test.py