name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  unit-test:
    name: 1. Unit Test Stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run Unit Tests
        run: pytest tests/unit_test.py


  linting:
    name: 2. Linting Stage
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: pip install flake8
      - name: Run Flake8
        run: flake8 src/


  package:
    name: 3. Docker Package Stage
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ml-service:latest .


  smoke-test:
    name: 4. Smoke Test Stage
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Container and Test
        run: |
          docker build -t ml-service:latest .
          docker run -d -p 5000:5000 --name prediction-service ml-service:latest
          sleep 15
          docker logs prediction-service
          pip install requests pytest
          pytest tests/smoke_test.py